### ISSUE TITLE
Database URL with hostname not accepted

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminus-javascript-sdk#2]
Only localhost is accepted as hostname for a database URL, but it does not work when using another entry in /etc/hosts.

The problem is in the URL parsing regex:

https://github.com/terminusdb/terminus-javascript-sdk/blob/11107c8aca2937bea3e65bff9b0349a0d6939677/WOQLClient.js#L774-L782

**Comment by kevinchekovfeeney** [comment]
Fixed in latest version
