### ISSUE TITLE
no way to return to document if you follow link

### ISSUE THREAD

**Issue by Anniepoo** [terminusdb/terminus-javascript-sdk#4]
Use the 'my first database' example at https://terminusdb.com/docs/my_first_terminusdb

1. follow until you make steve and john documents
2. view doc:steve
hmm.... john is steve's friend, I would like to know about john as part of learning about steve
3. click the doc:john link
EXPECTED: There would be a way back (a breadcrumb trail, making the back button work, or some 'return to prev document')
OBSERVED: No such way

**Comment by kevinchekovfeeney** [comment]
We have fixed this in 1.1 via 'back to documents' link
